name: call_qwik_example
description: "Demonstrates how to use the call_qwik plugin."

publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  country_picker: ^2.0.27
  custom_will_pop_scope: ^2.1.1
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  flutter_webrtc: ^1.2.1
  fluttertoast: ^9.0.0
  get: ^4.7.3
  google_fonts: ^6.3.3
  http: ^1.6.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  isometrik_call_flutter:
    path: ../
  just_audio: ^0.10.5
  livekit_client: ^2.6.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  pip_view: ^0.9.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
