name: call_qwik_example
description: "Demonstrates how to use the call_qwik plugin."

publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^7.0.0
  country_picker: ^2.0.26
  custom_will_pop_scope: ^2.1.1
  device_info_plus: ^11.3.3
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_callkit_incoming: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  fluttertoast: ^9.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  isometrik_call_flutter:
    path: ../
  just_audio: ^0.10.0
  livekit_client: ^2.5.1
  path_provider: ^2.1.3
  pin_code_fields: ^8.0.1
  pip_view: ^0.9.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  uuid: ^4.4.0

dependency_overrides:
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
