name: isometrik_call_flutter
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none
repository: https://github.com/isometrikai/isometrik-call-flutter

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.4.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  custom_will_pop_scope: ^2.1.1
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_callkit_incoming: ^2.0.4+2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  flutter_webrtc: ^0.14.1
  fluttertoast: ^8.2.6
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.20.1
  livekit_client:
    ^2.4.9
    # mqtt_helper: ^1.0.2
  mqtt_helper:
    git:
      url: https://github.com/rahulsaryam/mqtt_helper.git
      ref: main
  pip_view: ^0.9.7
  plugin_platform_interface: ^2.0.2
  pull_to_refresh: ^2.0.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.isometrik.isometrik_call_flutter
        pluginClass: IsometrikCallFlutterPlugin
      ios:
        pluginClass: IsometrikCallFlutterPlugin
        swift_version: 5.0
      web:
        pluginClass: IsometrikCallFlutterWeb
        fileName: isometrik_call_flutter_web.dart
  assets:
    - assets/
    - assets/icons/
