name: isometrik_call_flutter
description: "A new Flutter plugin project."
version: 0.0.1
repository: https://github.com/isometrikai/isometrik-call-flutter

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ai.isometrik.isometrik_call_flutter
        pluginClass: IsometrikCallFlutterPlugin
      ios:
        pluginClass: IsometrikCallFlutterPlugin
      web:
        pluginClass: IsometrikCallFlutterWeb
        fileName: isometrik_call_flutter_web.dart
